import { HexagramData } from './types';

// Mapping binary index to Hexagram info.
// The order follows the binary sequence (Bottom line is LSB or specific ordering).
// For simplicity in this implementation, we map standard King Wen sequence manually or use a simplified look up.
// Here we use a direct mapping array where index 0-63 corresponds to specific hexagrams.
// Note: To be truly random, we generate 6 lines.
// 0 = Yin (--), 1 = Yang (—).
// We will construct the array such that binary value matches the index if possible,
// or just use a flat list and pick by King Wen number logic if we were simulating coin tosses strictly.
// For this app, we simply define the 64 hexagrams in King Wen order for display,
// but we will select one randomly.

export const HEXAGRAMS: HexagramData[] = [
  { code: 1, name: "乾", symbol: "䷀", pinyin: "Qián", nature: "Heaven" },
  { code: 2, name: "坤", symbol: "䷁", pinyin: "Kūn", nature: "Earth" },
  { code: 3, name: "屯", symbol: "䷂", pinyin: "Zhūn", nature: "Difficulty at the Beginning" },
  { code: 4, name: "蒙", symbol: "䷃", pinyin: "Méng", nature: "Youthful Folly" },
  { code: 5, name: "需", symbol: "䷄", pinyin: "Xū", nature: "Waiting" },
  { code: 6, name: "讼", symbol: "䷅", pinyin: "Sòng", nature: "Conflict" },
  { code: 7, name: "师", symbol: "䷆", pinyin: "Shī", nature: "The Army" },
  { code: 8, name: "比", symbol: "䷇", pinyin: "Bǐ", nature: "Holding Together" },
  { code: 9, name: "小畜", symbol: "䷈", pinyin: "Xiǎo Chù", nature: "Small Taming" },
  { code: 10, name: "履", symbol: "䷉", pinyin: "Lǚ", nature: "Treading" },
  { code: 11, name: "泰", symbol: "䷊", pinyin: "Tài", nature: "Peace" },
  { code: 12, name: "否", symbol: "䷋", pinyin: "Pǐ", nature: "Standstill" },
  { code: 13, name: "同人", symbol: "䷌", pinyin: "Tóng Rén", nature: "Fellowship" },
  { code: 14, name: "大有", symbol: "䷍", pinyin: "Dà Yǒu", nature: "Great Possession" },
  { code: 15, name: "谦", symbol: "䷎", pinyin: "Qiān", nature: "Modesty" },
  { code: 16, name: "豫", symbol: "䷏", pinyin: "Yù", nature: "Enthusiasm" },
  { code: 17, name: "随", symbol: "䷐", pinyin: "Suí", nature: "Following" },
  { code: 18, name: "蛊", symbol: "䷑", pinyin: "Gǔ", nature: "Work on Decayed" },
  { code: 19, name: "临", symbol: "䷒", pinyin: "Lín", nature: "Approach" },
  { code: 20, name: "观", symbol: "䷓", pinyin: "Guān", nature: "Contemplation" },
  { code: 21, name: "噬嗑", symbol: "䷔", pinyin: "Shì Kè", nature: "Biting Through" },
  { code: 22, name: "贲", symbol: "䷕", pinyin: "Bì", nature: "Grace" },
  { code: 23, name: "剥", symbol: "䷖", pinyin: "Bō", nature: "Splitting Apart" },
  { code: 24, name: "复", symbol: "䷗", pinyin: "Fù", nature: "Return" },
  { code: 25, name: "无妄", symbol: "䷘", pinyin: "Wú Wàng", nature: "Innocence" },
  { code: 26, name: "大畜", symbol: "䷙", pinyin: "Dà Chù", nature: "Great Taming" },
  { code: 27, name: "颐", symbol: "䷚", pinyin: "Yí", nature: "Mouth Corners" },
  { code: 28, name: "大过", symbol: "䷛", pinyin: "Dà Guò", nature: "Great Preponderance" },
  { code: 29, name: "坎", symbol: "䷜", pinyin: "Kǎn", nature: "The Abysmal" },
  { code: 30, name: "离", symbol: "䷝", pinyin: "Lí", nature: "The Clinging" },
  { code: 31, name: "咸", symbol: "䷞", pinyin: "Xián", nature: "Influence" },
  { code: 32, name: "恒", symbol: "䷟", pinyin: "Héng", nature: "Duration" },
  { code: 33, name: "遁", symbol: "䷠", pinyin: "Dùn", nature: "Retreat" },
  { code: 34, name: "大壮", symbol: "䷡", pinyin: "Dà Zhuàng", nature: "Great Power" },
  { code: 35, name: "晋", symbol: "䷢", pinyin: "Jìn", nature: "Progress" },
  { code: 36, name: "明夷", symbol: "䷣", pinyin: "Míng Yí", nature: "Darkening of the Light" },
  { code: 37, name: "家人", symbol: "䷤", pinyin: "Jiā Rén", nature: "The Family" },
  { code: 38, name: "睽", symbol: "䷥", pinyin: "Kuí", nature: "Opposition" },
  { code: 39, name: "蹇", symbol: "䷦", pinyin: "Jiǎn", nature: "Obstruction" },
  { code: 40, name: "解", symbol: "䷧", pinyin: "Xiè", nature: "Deliverance" },
  { code: 41, name: "损", symbol: "䷨", pinyin: "Sǔn", nature: "Decrease" },
  { code: 42, name: "益", symbol: "䷩", pinyin: "Yì", nature: "Increase" },
  { code: 43, name: "夬", symbol: "䷪", pinyin: "Guài", nature: "Break-through" },
  { code: 44, name: "姤", symbol: "䷫", pinyin: "Gòu", nature: "Coming to Meet" },
  { code: 45, name: "萃", symbol: "䷬", pinyin: "Cuì", nature: "Gathering Together" },
  { code: 46, name: "升", symbol: "䷭", pinyin: "Shēng", nature: "Pushing Upward" },
  { code: 47, name: "困", symbol: "䷮", pinyin: "Kùn", nature: "Oppression" },
  { code: 48, name: "井", symbol: "䷯", pinyin: "Jǐng", nature: "The Well" },
  { code: 49, name: "革", symbol: "䷰", pinyin: "Gé", nature: "Revolution" },
  { code: 50, name: "鼎", symbol: "䷱", pinyin: "Dǐng", nature: "The Cauldron" },
  { code: 51, name: "震", symbol: "䷲", pinyin: "Zhèn", nature: "The Arousing" },
  { code: 52, name: "艮", symbol: "䷳", pinyin: "Gèn", nature: "Keeping Still" },
  { code: 53, name: "渐", symbol: "䷴", pinyin: "Jiàn", nature: "Development" },
  { code: 54, name: "归妹", symbol: "䷵", pinyin: "Guī Mèi", nature: "The Marrying Maiden" },
  { code: 55, name: "丰", symbol: "䷶", pinyin: "Fēng", nature: "Abundance" },
  { code: 56, name: "旅", symbol: "䷷", pinyin: "Lǚ", nature: "The Wanderer" },
  { code: 57, name: "巽", symbol: "䷸", pinyin: "Xùn", nature: "The Gentle" },
  { code: 58, name: "兑", symbol: "䷹", pinyin: "Duì", nature: "The Joyous" },
  { code: 59, name: "涣", symbol: "䷺", pinyin: "Huàn", nature: "Dispersion" },
  { code: 60, name: "节", symbol: "䷻", pinyin: "Jié", nature: "Limitation" },
  { code: 61, name: "中孚", symbol: "䷼", pinyin: "Zhōng Fú", nature: "Inner Truth" },
  { code: 62, name: "小过", symbol: "䷽", pinyin: "Xiǎo Guò", nature: "Small Preponderance" },
  { code: 63, name: "既济", symbol: "䷾", pinyin: "Jì Jì", nature: "After Completion" },
  { code: 64, name: "未济", symbol: "䷿", pinyin: "Wèi Jì", nature: "Before Completion" },
];
